name: Build and Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libboost-all-dev libgtest-dev flex libfl-dev cmake
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: CMake config
      run: |
        export PATH=/usr/local/bison/bin/:$PATH
        cmake -S ./ -B build -DCMAKE_BUILD_TYPE=Release -DNOGTEST=OFF

    - name: CMake build
      run: |
        cmake --build build

    - name: CMake test
      run: |
        env CTEST_OUTPUT_ON_FAILURE=1
        cmake --build build --target test